import { AppWindow } from "../app-window.slint";

export component AppWindowPreview inherits AppWindow {
    gif-image: @image-url("../トレサ.png");
    gif-frame-count: 42;
    frames: [
        @image-url("../トレサ.png"),
        @image-url("../トレサ.png"),
        @image-url("../トレサ.png"),
        @image-url("../トレサ.png"),
        @image-url("../トレサ.png"),
        @image-url("../トレサ.png"),
        @image-url("../トレサ.png"),
        @image-url("../トレサ.png"),
        @image-url("../トレサ.png"),
    ];
}
