import { AppWindow } from "../app-window.slint";

export component AppWindowPreview inherits AppWindow {
    frames: [
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
        { image: @image-url("../トレサ.png"), delay: 10 },
    ];
}
