import { EditFrameDropWindow } from "../edit-frame-drop-window.slint";

export component EditFrameDropWindowPreview inherits EditFrameDropWindow {
    current-total-frames: 20;
    frame-drop-interval: 3;
    frame-drop-start-index: 3;
    frames: [
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
        { image: @image-url("../トレサ.png") },
    ];
}
