[package]
name = "gif-ide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.102"
gif = "0.14.2"
rfd = "0.17.2"
slint = "1.16.1"
tokio = { version = "1.52.3", features = ["rt-multi-thread"] }

[build-dependencies]
slint-build = "1.16.1"

[profile.release]
codegen-units = 1
lto = true
