import {
    Button,
    Spinner,
    Palette,
    ScrollView,
    AboutSlint,
    LineEdit,
    SpinBox,
} from "std-widgets.slint";
import { Style } from "global-styles.slint";
export { MessageDialog } from "message-dialog.slint";
export { ExportFileWindow } from "export-file-window.slint";
export { ImportFileWindow } from "import-file-window.slint";
export { EditFrameDropWindow, FramePreview } from "edit-frame-drop-window.slint";
export { EditCanvasResizeWindow } from "edit-canvas-resize-window.slint";
export { LoadingState } from "loading-state.slint";
// ThemeはWindowごとに保有されるため、ExportしてDialogを開く際にThemeを必ず渡す
export { Palette } from "std-widgets.slint";

struct FrameData {
    image: image,
    delay: int,
}

export component AppWindow inherits Window {
    in-out property <int> current-tab: 0;
    in property <[FrameData]> frames: [];
    in-out property <int> selected-frame-index: 0;
    in property <bool> is-loading: false;
    in-out property <bool> is-play: false;
    in-out property <bool> is-repeat: true;
    in property <string> filename: "";
    in property <int> gif-canvas-width: 0;
    in property <int> gif-canvas-height: 0;
    in-out property <length> sidebar-width: 200px;
    in property <string> current-language: "ja";
    callback import-file();
    callback export-file();
    callback play(int);
    callback apply-delay-to-all(int);
    callback frame-delay-changed(int, float);
    callback edit-frame-drop;
    callback edit-canvas-resize;
    callback switch-language();

    title: "GIF IDE";
    default-font-family: Style.font-family;
    preferred-height: 560px;
    preferred-width: 900px;

    VerticalLayout {
        // Header
        HorizontalLayout {
            alignment: space-between;
            padding: 12px;
            spacing: 20px;

            VerticalLayout {
                alignment: center;
                Text {
                    text: "GIF IDE";
                    font-size: 16px;
                }
            }

            // Language & Theme Buttons
            HorizontalLayout {
                spacing: 8px;

                VerticalLayout {
                    alignment: center;

                    Button {
                        text: current-language == "en" ? "JA" : "EN";
                        clicked => {
                            root.switch-language();
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    Button {
                        icon: Palette.color-scheme == ColorScheme.dark ? @image-url("assets/sun.svg") : @image-url("assets/moon.svg");
                        colorize-icon: true;
                        clicked => {
                            if (Palette.color-scheme == ColorScheme.dark) {
                                Palette.color-scheme = ColorScheme.light;
                            } else {
                                Palette.color-scheme = ColorScheme.dark;
                            }
                        }
                    }
                }
            }
        }

        Rectangle {
            height: 1px;
            background: Palette.foreground.transparentize(0.7);
        }

        HorizontalLayout {
            // Main Display
            VerticalLayout {
                // Image Display
                VerticalLayout {
                    vertical-stretch: 1;
                    padding: 12px;

                    if !is-loading && frames.length == 0: Button {
                        text: @tr("ファイル選択");
                        clicked => root.import-file();
                    }

                    if is-loading: Spinner {
                        indeterminate: true;
                    }

                    if frames.length > 0: Image {
                        source: frames[selected-frame-index].image;
                    }
                }

                // Play Bar
                VerticalLayout {
                    alignment: center;
                    vertical-stretch: 0;

                    Rectangle {
                        height: 1px;
                        background: Palette.foreground.transparentize(0.7);
                    }

                    HorizontalLayout {
                        alignment: center;
                        padding: 12px;
                        spacing: 12px;

                        VerticalLayout {
                            alignment: center;
                            Button {
                                icon: @image-url("assets/skip-back.svg");
                                colorize-icon: true;
                                enabled: frames.length > 0;
                                clicked => {
                                    root.selected-frame-index = 0;
                                }
                            }
                        }

                        VerticalLayout {
                            alignment: center;
                            Button {
                                icon: @image-url("assets/step-back.svg");
                                colorize-icon: true;
                                enabled: frames.length > 0;
                                clicked => {
                                    let prev = selected-frame-index - 1;
                                    root.selected-frame-index = prev < 0 ? frames.length - 1 : prev;
                                }
                            }
                        }

                        VerticalLayout {
                            alignment: center;
                            Button {
                                icon: is-play ? @image-url("assets/stop.svg") : @image-url("assets/play.svg");
                                colorize-icon: true;
                                primary: true;
                                enabled: frames.length > 0;
                                clicked => {
                                    is-play = !is-play;
                                    root.play(selected-frame-index);
                                }
                            }
                        }

                        VerticalLayout {
                            alignment: center;
                            Button {
                                icon: @image-url("assets/step-forward.svg");
                                colorize-icon: true;
                                enabled: frames.length > 0;
                                clicked => {
                                    let next = selected-frame-index + 1;
                                    root.selected-frame-index = next >= frames.length ? 0 : next;
                                }
                            }
                        }

                        VerticalLayout {
                            alignment: center;
                            Button {
                                icon: @image-url("assets/skip-forward.svg");
                                colorize-icon: true;
                                enabled: frames.length > 0;
                                clicked => {
                                    root.selected-frame-index = frames.length - 1;
                                }
                            }
                        }

                        VerticalLayout {
                            alignment: center;
                            Button {
                                icon: @image-url("assets/repeat.svg");
                                colorize-icon: true;
                                primary: is-repeat;
                                clicked => {
                                    is-repeat = !is-repeat;
                                }
                            }
                        }
                    }

                    Rectangle {
                        height: 1px;
                        background: Palette.foreground.transparentize(0.7);
                    }
                }

                // Frame Bar
                VerticalLayout {
                    alignment: center;
                    vertical-stretch: 0;
                    padding: 12px;
                    spacing: 10px;

                    property <length> fling-velocity: 0px;

                    inertia-timer := Timer {
                        interval: 16ms;
                        triggered => {
                            let max-scroll = frame-list.preferred-width - frame-scroll.visible-width;
                            frame-scroll.viewport-x = clamp(frame-scroll.viewport-x + fling-velocity, -max-scroll, 0px);
                            fling-velocity = fling-velocity * 0.92;
                            if (abs(fling-velocity) < 0.5px) {
                                self.running = false;
                            }
                        }
                    }

                    if frames.length != 0: VerticalLayout {
                        HorizontalLayout {
                            alignment: start;
                            spacing: 8px;
                            bulk-delay-input := LineEdit {
                                width: 64px;
                                horizontal-alignment: center;
                                text: 0;
                                input-type: number;
                                enabled: !is-play;
                                edited(text) => {
                                    if (text.is-float()) {
                                        self.text = Math.clamp(text.to-float(), 0, 6000);
                                    } else {
                                        self.text = 0;
                                    }
                                }
                                accepted(text) => {
                                    self.clear-focus();
                                    apply-delay.clicked();
                                }
                            }

                            apply-delay := Button {
                                text: @tr("delay一括適用");
                                enabled: !is-play;
                                clicked => {
                                    bulk-delay-input.clear-focus();
                                    root.apply-delay-to-all(bulk-delay-input.text.to-float());
                                }
                            }
                        }
                    }

                    frame-scroll := ScrollView {
                        viewport-width: frame-list.preferred-width;
                        height: frame-list.preferred-height;

                        frame-list := HorizontalLayout {
                            alignment: start;
                            spacing: 8px;
                            padding-bottom: 22px;
                            for frame[i] in frames: VerticalLayout {
                                property <bool> is-dragging: false;

                                frame-touch-area := TouchArea {
                                    // フリックスクロール動作
                                    mouse-cursor: self.pressed ? MouseCursor.grabbing : MouseCursor.grab;
                                    pointer-event(e) => {
                                        if (e.kind == PointerEventKind.down) {
                                            is-dragging = false;
                                            fling-velocity = 0px;
                                            inertia-timer.running = false;
                                        }
                                        if (e.kind == PointerEventKind.up && is-dragging) {
                                            if (abs(fling-velocity) > 1px) {
                                                inertia-timer.running = true;
                                            }
                                        }
                                    }
                                    moved => {
                                        let dx = self.mouse-x - self.pressed-x;
                                        if (abs(dx) > 4px || is-dragging) {
                                            is-dragging = true;
                                            let prev-x = frame-scroll.viewport-x;
                                            let max-scroll = frame-list.preferred-width - frame-scroll.visible-width;
                                            frame-scroll.viewport-x = clamp(frame-scroll.viewport-x + dx, -max-scroll, 0px);
                                            fling-velocity = frame-scroll.viewport-x - prev-x;
                                        }
                                    }
                                    clicked => {
                                        if (!is-dragging) {
                                            root.selected-frame-index = i;
                                        }
                                    }

                                    VerticalLayout {
                                        width: 64px;
                                        spacing: 10px;

                                        Rectangle {
                                            height: 50px;
                                            border-width: 1px;
                                            border-color: root.selected-frame-index == i ? Palette.accent-background : frame-touch-area.has-hover ? Palette.accent-background.transparentize(0.5) : Palette.foreground.transparentize(0.7);
                                            border-radius: 4px;
                                            clip: true;

                                            Image {
                                                width: parent.width;
                                                height: parent.height;
                                                source: frame.image;
                                                image-fit: cover;
                                            }

                                            Rectangle {
                                                x: 4px;
                                                y: parent.height - self.height - 4px;
                                                width: num.preferred-width + 6px;
                                                height: num.preferred-height + 2px;
                                                border-radius: 2px;
                                                background: Palette.background.transparentize(0.3);

                                                num := Text {
                                                    x: 3px;
                                                    font-size: 10px;
                                                    color: Palette.foreground;
                                                    text: i + 1;
                                                }
                                            }
                                        }

                                        VerticalLayout {
                                            alignment: center;
                                            LineEdit {
                                                height: 20px;
                                                width: 64px;
                                                horizontal-alignment: center;
                                                text: frame.delay;
                                                input-type: number;
                                                enabled: !is-play;
                                                edited(text) => {
                                                    if (text.is-float()) {
                                                        self.text = Math.clamp(text.to-float(), 0, 6000);
                                                    } else {
                                                        self.text = 0;
                                                    }
                                                    root.frame-delay-changed(i, self.text.to-float());
                                                }
                                                accepted(text) => {
                                                    self.clear-focus();
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // Divider
            Rectangle {
                width: 5px;

                Rectangle {
                    width: 1px;
                    height: 100%;
                    x: (parent.width - self.width) / 2;
                    background: Palette.foreground.transparentize(0.7);
                }

                TouchArea {
                    mouse-cursor: col-resize;
                    property <length> start-abs-x: 0px;
                    property <length> start-sidebar-width: 0px;

                    pointer-event(e) => {
                        if (e.kind == PointerEventKind.down) {
                            start-abs-x = self.absolute-position.x + self.mouse-x;
                            start-sidebar-width = root.sidebar-width;
                        }
                    }

                    moved => {
                        root.sidebar-width = max(60px, min(500px,
                            start-sidebar-width - (self.absolute-position.x + self.mouse-x - start-abs-x)));
                    }
                }
            }

            // Side Bar
            VerticalLayout {
                width: root.sidebar-width;
                alignment: space-between;

                VerticalLayout {
                    // File Info
                    VerticalLayout {
                        padding: 12px;
                        spacing: 4px;
                        alignment: center;

                        // 小見出し
                        Text {
                            text: @tr("GIF 情報");
                            font-size: 13px;
                            font-weight: FontWeight.medium;
                            color: Palette.foreground.transparentize(0.3);
                        }

                        // ファイル名
                        HorizontalLayout {
                            alignment: space-between;

                            Text {
                                text: @tr("ファイル名");
                                color: Palette.foreground.transparentize(0.5);
                                vertical-alignment: center;
                            }

                            Text {
                                text: filename == "" ? "---" : filename;
                                color: Palette.foreground.transparentize(0.5);
                                vertical-alignment: center;
                            }
                        }

                        // 総フレーム数
                        HorizontalLayout {
                            alignment: space-between;

                            Text {
                                text: @tr("総フレーム数");
                                color: Palette.foreground.transparentize(0.5);
                                vertical-alignment: center;
                            }

                            Text {
                                text: frames.length == 0 ? "---" : frames.length;
                                color: Palette.foreground.transparentize(0.5);
                                vertical-alignment: center;
                            }
                        }

                        // GIF Canvasサイズ
                        HorizontalLayout {
                            alignment: space-between;

                            Text {
                                text: @tr("サイズ");
                                color: Palette.foreground.transparentize(0.5);
                                vertical-alignment: center;
                            }

                            Text {
                                text: gif-canvas-width == 0 ? "---" : gif-canvas-width + " x " + gif-canvas-height;
                                color: Palette.foreground.transparentize(0.5);
                                vertical-alignment: center;
                            }
                        }
                    }

                    Rectangle {
                        height: 1px;
                        background: Palette.foreground.transparentize(0.7);
                    }

                    // Edit
                    VerticalLayout {
                        padding: 12px;
                        spacing: 8px;
                        alignment: center;

                        // 小見出し
                        Text {
                            text: @tr("編集");
                            font-size: 13px;
                            font-weight: FontWeight.medium;
                            color: Palette.foreground.transparentize(0.3);
                        }

                        // キャンバスリサイズ
                        Button {
                            text: @tr("キャンバスをリサイズ");
                            enabled: !is-play && frames.length > 0;
                            clicked => {
                                root.edit-canvas-resize();
                            }
                        }

                        // 間引く
                        Button {
                            text: @tr("フレームを間引く");
                            enabled: !is-play && frames.length > 0;
                            clicked => {
                                root.edit-frame-drop();
                            }
                        }
                    }

                    Rectangle {
                        height: 1px;
                        background: Palette.foreground.transparentize(0.7);
                    }

                    // Export
                    VerticalLayout {
                        padding: 12px;
                        spacing: 8px;
                        alignment: center;

                        // 小見出し
                        Text {
                            text: @tr("入力/出力");
                            font-size: 13px;
                            font-weight: FontWeight.medium;
                            color: Palette.foreground.transparentize(0.3);
                        }

                        Button {
                            text: @tr("ファイル選択");
                            enabled: !is-play;
                            clicked => {
                                root.import-file();
                            }
                        }

                        Button {
                            text: @tr("出力");
                            primary: true;
                            enabled: !is-play && frames.length > 0;
                            clicked => {
                                root.export-file();
                            }
                        }
                    }

                    Rectangle {
                        height: 1px;
                        background: Palette.foreground.transparentize(0.7);
                    }
                }

                VerticalLayout {
                    padding-bottom: 10px;
                    AboutSlint {
                        height: 100px;
                    }
                }
            }
        }
    }
}
