import {
    ScrollView,
    StandardButton,
    LineEdit,
    Button,
    Slider,
    ComboBox,
    Spinner,
    Palette,
    Switch,
} from "std-widgets.slint";
import { SelectionGroup } from "selection-group.slint";
import { Style } from "global-styles.slint";
import { LoadingState } from "loading-state.slint";

export component ExportFileWindow inherits Window {
    in-out property <int> format-index: 0;
    in-out property <string> export-path: "";
    out property <bool> is-gif: format-index == 0;
    out property <bool> is-jpeg: format-index == 2;
    in-out property <bool> gif-loop-forever: true;
    in-out property <bool> gif-optimize: false;
    in-out property <int> range-index: 0;
    in-out property <float> quality: 100;
    in property <LoadingState> state: LoadingState.form;
    in property <int> progress-current: 0;
    in property <int> progress-total: 0;
    callback select-export-path();
    callback start-export();
    callback cancel();
    callback open-export-folder();

    // FileDialogと干渉するため設定しないこと
    // always-on-top: true;
    title: "ファイル出力";
    default-font-family: Style.font-family;
    height: self.preferred-height;

    VerticalLayout {
        padding: 16px;
        spacing: 16px;

        if root.state == LoadingState.success: Rectangle {
            background: Colors.green.transparentize(0.85);
            border-radius: 6px;

            HorizontalLayout {
                padding: 10px;
                spacing: 10px;
                alignment: space-between;

                HorizontalLayout {
                    spacing: 10px;
                    alignment: start;

                    Image {
                        source: @image-url("assets/check.svg");
                        colorize: Colors.green;
                        width: 16px;
                        height: 16px;
                    }

                    Text {
                        text: "出力に成功しました";
                        vertical-alignment: center;
                        color: Colors.darkgreen;
                    }
                }

                TouchArea {
                    width: open-text.preferred-width;
                    height: open-text.preferred-height;
                    mouse-cursor: pointer;
                    clicked => {
                        root.open-export-folder();
                    }

                    open-text := Text {
                        text: "開く";
                        vertical-alignment: center;
                        color: Palette.accent-background;
                    }
                }
            }
        }

        VerticalLayout {
            spacing: 10px;
            Text {
                text: "形式";
                font-size: 14px;
                font-weight: FontWeight.medium;
                vertical-alignment: center;
            }

            ComboBox {
                model: ["GIF", "PNG", "JPEG", "WEBP", "BMP", "ICO", "AVIF"];
                current-index <=> root.format-index;
                selected(current-value) => {
                    root.export-path = "";
                }
            }
        }

        VerticalLayout {
            spacing: 10px;
            Text {
                text: "保存先";
                font-size: 14px;
                font-weight: FontWeight.medium;
                vertical-alignment: center;
            }

            HorizontalLayout {
                spacing: 10px;

                LineEdit {
                    text <=> root.export-path;
                }

                Button {
                    icon: @image-url("assets/folder-open.svg");
                    colorize-icon: true;
                    clicked => {
                        root.select-export-path();
                    }
                }
            }
        }

        if !root.is-gif: VerticalLayout {
            spacing: 10px;
            Text {
                text: "範囲";
                font-size: 14px;
                font-weight: FontWeight.medium;
                vertical-alignment: center;
            }

            SelectionGroup {
                options: ["現在のフレーム", "すべて"];
                selected-index <=> root.range-index;
            }
        }

        if root.is-gif: HorizontalLayout {
            padding-top: 5px;
            spacing: 10px;
            Switch {
                text: "ループ";
                checked: gif-loop-forever;
                toggled => {
                    gif-loop-forever = !gif-loop-forever;
                }
            }
            Switch {
                text: "サイズ最適化 (不透明な内容のみ効果あり)";
                checked: gif-optimize;
                toggled => {
                    gif-optimize = !gif-optimize;
                }
            }
        }

        if root.is-jpeg: VerticalLayout {
            spacing: 10px;

            HorizontalLayout {
                alignment: start;
                spacing: 8px;
                Text {
                    text: "品質";
                    font-size: 14px;
                    font-weight: FontWeight.medium;
                    vertical-alignment: center;
                }

                Text {
                    text: round(root.quality);
                    font-size: 14px;
                    vertical-alignment: center;
                }
            }

            HorizontalLayout {
                spacing: 4px;

                Text {
                    text: "0";
                }

                Slider {
                    minimum: 0;
                    maximum: 100;
                    step: 1;
                    value <=> root.quality;
                }

                Text {
                    text: "100";
                }
            }
        }

        HorizontalLayout {
            alignment: end;
            padding-top: 10px;
            spacing: 10px;

            if root.state == LoadingState.form || root.state == LoadingState.success: Button {
                text: "OK";
                primary: true;
                enabled: root.export-path != "";
                clicked => {
                    root.start-export();
                }
            }

            if root.state == LoadingState.processing: HorizontalLayout {
                spacing: 8px;
                Spinner {
                    indeterminate: true;
                }
                if root.progress-total > 0: Text {
                    text: root.progress-current + " / " + root.progress-total;
                    vertical-alignment: center;
                }
            }

            Button {
                text: "Cancel";
                enabled: root.state == LoadingState.form || root.state == LoadingState.success;
                clicked => {
                    root.cancel();
                }
            }
        }
    }
}
