import {
    ScrollView,
    StandardButton,
    LineEdit,
    Button,
    Slider,
    ComboBox,
    Spinner,
} from "std-widgets.slint";
import { SelectionGroup } from "selection-group.slint";

export enum ExportState {
    form,
    processing,
}

export component ExportImageDialog inherits Dialog {
    in-out property <int> format-index: 0;
    in-out property <int> range-index: 0;
    out property <bool> is-jpeg: format-index == 1;
    in-out property <string> save-path: "";
    in property <ExportState> state: ExportState.form;
    callback ok-clicked();
    callback pick-path();

    // FileDialogと干渉するため設定しないこと
    // always-on-top: true;
    padding: 16px;
    title: "画像出力";
    height: self.preferred-height;

    VerticalLayout {
        if root.state == ExportState.form: VerticalLayout {
            padding-bottom: 10px;
            spacing: 20px;

            VerticalLayout {
                spacing: 10px;
                Text {
                    text: "形式";
                    font-size: 14px;
                    font-weight: FontWeight.medium;
                    vertical-alignment: center;
                }

                ComboBox {
                    model: ["PNG", "JPEG", "WEBP", "BMP", "ICO", "AVIF"];
                    current-index <=> root.format-index;
                }
            }

            VerticalLayout {
                spacing: 10px;
                Text {
                    text: "範囲";
                    font-size: 14px;
                    font-weight: FontWeight.medium;
                    vertical-alignment: center;
                }

                SelectionGroup {
                    options: ["現在のフレーム", "すべて"];
                    selected-index <=> root.range-index;
                }
            }

            VerticalLayout {
                spacing: 10px;
                Text {
                    text: "保存先";
                    font-size: 14px;
                    font-weight: FontWeight.medium;
                    vertical-alignment: center;
                }

                HorizontalLayout {
                    spacing: 10px;

                    LineEdit {
                        text <=> root.save-path;
                    }

                    Button {
                        icon: @image-url("assets/folder-open.svg");
                        colorize-icon: true;
                        clicked => {
                            root.pick-path();
                        }
                    }
                }
            }

            if root.is-jpeg: VerticalLayout {
                spacing: 10px;

                Text {
                    text: "品質";
                    font-size: 14px;
                    font-weight: FontWeight.medium;
                    vertical-alignment: center;
                }

                HorizontalLayout {
                    Text {
                        text: "0";
                        vertical-alignment: center;
                    }

                    Slider {
                        minimum: 0;
                        maximum: 100;
                        step: 1;
                        value: 50;
                    }

                    Text {
                        text: "100";
                        vertical-alignment: center;
                    }
                }
            }
        }

        if root.state == ExportState.processing: VerticalLayout {
            alignment: center;
            padding: 30px;
            spacing: 10px;

            Spinner {
                indeterminate: true;
            }

            Text {
                text: "出力中...";
                horizontal-alignment: center;
            }
        }
    }

    StandardButton {
        kind: ok;
        primary: true;
        enabled: root.state == ExportState.form;
        clicked => {
            root.ok-clicked();
        }
    }

    StandardButton {
        kind: cancel;
        enabled: root.state == ExportState.form;
    }
}
