import { ScrollView, StandardButton } from "std-widgets.slint";
import { Style } from "global-styles.slint";
export component MessageDialog inherits Dialog {
    in property <string> title-text;
    in property <string> message;
    callback close();

    always-on-top: true;
    preferred-width: 500px;
    padding: 16px;
    title: title-text;
    icon: @image-url("assets/window-icon.png");
    default-font-family: Style.font-family;

    VerticalLayout {
        padding-bottom: 10px;

        ScrollView {
            preferred-height: min(msg-text.preferred-height, 200px);
            viewport-height: msg-text.preferred-height;

            msg-text := Text {
                text: message;
                wrap: word-wrap;
                width: parent.visible-width - 16px;
            }
        }
    }

    StandardButton {
        kind: ok;
        primary: true;
        clicked => {
            root.close();
        }
    }
}
